sindresorhus/memoize

- index.js
- test.js
As described in #3, when the first argument was a primitive, it always took that argument as the only key in the cache because of `typeof x !== 'function' && typeof x !== 'object'`.
> fix default cacheKey - fixes #3

- index.js
- package.json
- readme.md
- test.js
This PR fixes #8 by not caching a rejected promise by default. I also added a `cacheRejection` option (couldn't come up with a better name) to re-enable it.
Feedback welcome!
> Don't cache rejected promises - fixes #8

- index.js
- readme.md
- test.js
Fixes issue discussed in #10 
This should probably go out as a semver major since we are putting additional requirements on the cache object and since the previous behaviour, although not intentionally added, might already be relied on...
> Cache pending promises

- index.js
- test.js
Related to #14 although it might not fix it explicitly. 
This explicitly calls `delete()` if the max age has passed, so that if passing a caching object that is maybe different to `Map` then it doesn't rely on `set()` in order to actually remove old entries.
This also fixes a bug where if a subsequent call to `fn` may throw an error (even if the original call did not - perhaps because some side-effect has changed, e.g. a filesystem - causing `fn` to now throw) - then the `.set` was never called and so older entries would remain without ever being explicitly cleared up.
> Delete cache entries older than max age

- index.js
A few minor performance enhancements
- Don't look in the `cacheStore` on every function call, keep in local variable
- Don't recreate `setData` function on every function call
- Set a default key for when `args` is empty instead of calling JSON.stringify
- Calculate some parameters for `maxAge` logic ahead of time
Results:
`8.3x` speedup for empty arguments
`1.86x` speedup for single arguments
`1.1x` speedup for complex arguments
Benchmark Code:
```
const mp = require('./perf');
const m = require('./index');
const argSets = [
[],
[0],
['foo', 'bar', 'baz'],
[{foo: true}, {bar: false}]
];
const scenarios = [
{
mem: mp,
name: 'Perf    ',
},
{
mem: m,
name: 'Original'
}
];
const N = 1e8;
for (let args of argSets) {
for (let {mem, name} of scenarios) {
let i = 0;
const f = () => i++;
const …
```
> Performance enhancements

- index.js
- package.json
- readme.md
- test.js
This PR fixes #14 by using [map-age-cleaner](https://github.com/SamVerschueren/map-age-cleaner) which removes item when it expires.
> Automatically release memory when an item expires - fixes #14

- test.js
Add tests for #20.
CI tests will fail in `memoize with regexp arguments` and `memoize with Symbol arguments`.
> Add failing tests for RegExp and Symbol arguments

- index.d.ts
- index.test-d.ts
@sindresorhus Thanks for adding types to your repos! 
I believe the `cache` type needs to include the `data`, otherwise this isn't possible:
```typescript
const cache = new QuickLRU<string, { data: Bundle }>({
maxSize: BUNDLE_COUNT_TO_MEMORIZE
});
const loadJsonFileMemorized = mem(
(filename: string) => loadJsonFile<Bundle>(filename),
{
cache
}
);
// After modifying we want to update the cache directly to avoid another load.
cache.set(filename, { data: updatedBundle });
```
> TypeScript - Fix the cache type

- index.d.ts
- index.js
- readme.md
- test.js
Since the very first version, mem has a _"cache if it's not a function AND not an object"_, which I don't understand because functions are can't be serialized via `JSON.stringify`
In short (unless I'm drunk 🤔) I think `mem` should _always_ use the ONE argument as key, unless it's a serializable object.
> Cache function reference when it's a single argument

- index.d.ts
- index.js
- readme.md
- test.js
As a feature, this already feels weird because caching depends on this specific mechanism and not others like:
- should the function be cached if it returns `false`?
- should the function be cached if its call parameters include `{cache: false}`?
Having it avoid cache just because a promise is rejected feels arbitrary... but in a way I see that it's a flexible mechanism that allows any function (sync or async) to decide whether to avoid the cache.
That said, I don't think it should be a default, because:
- there's a chance that if something errors the first time, it will also error the second time (idempotency is a virtue);
- seen as a mechanism to avoid cache, it should be opt-in if needed, rather than an opaque behavior the developer didn't ask for.
> Change the default value of the `cachePromiseRejection` option to `true`

- index.js
- test.js
This aligns the behavior with `p-memoize`, if it's desirable.
Breaking change
> Throw when `.clear()` is called with a non-memoized function

- index.d.ts
- index.js
- index.test-d.ts
- package.json
- readme.md
- test.js
Implements and closes #40 
Replaces and closes #22
Fixes #20
(Basically merging this PR will close everything in this repo 🎉)
In short, what used to be known as `cacheKey: x => x` is now the default.
This default aligns `mem` with other common memoize implementations (like lodash) while still supporting and suggesting a variety of serialization methods which the user can pick.
This makes the memoization logic very straightforward, explicit and fast by default. Refer to [the new readme](https://github.com/sindresorhus/mem/tree/ede5403a634cbe40fc8e36b71644ceebf439501e#cachekey)
---
The main API change is the new signature of `cacheKey`, which instead of receiving the arguments as `cacheKey(...arguments_)`, it receives them as an array. This change makes it easy to supply a plain serializer …
> Simplify default serializer; drop promise-related option

- index.js
- readme.md
`mem` doesn't **_need_** `Map`, it's just that `WeakMap` doesn't support most primitives. If it could, it should _only_ use `WeakMap`
Proposal: use `WeakMap`...
- if `cache` isn't provided by the user
- when the current `key` is supported by `WeakMap`
This is automatic and silent.
> Automatically use WeakMap when possible

- .travis.yml
- index.d.ts
- index.js
- package.json
- test-d/index.test-d.ts
- test.js
I wanted to make #64 more granular. This PR:
- updates AVA and adjusts the tests for it
- updates XO and applies the new lints
- moves tsd tests to sub-directory 
- adjusts/fixes some expected types to make it tsd pass
> Update dependencies and require Node.js 10

- index.ts
- test.js
Breaking change, to be released after #58 (which is a patch for the current version)
What's the point of calling `clear(fn)` if it does nothing? This just causes silent errors.
Regarding throwing errors:
- I can **drop** the explicit `Can't clear a function that was not memoized!` error since now it throws anyway, OR
- I can **add** an `unclearable cache` error
> Throw on clear(fn) if fn’s cache can't be cleared

- index.ts
https://github.com/sindresorhus/mimic-fn/pull/34 avoids this error, is that correct?
> Avoid `mimicFn` error without try/catch

- index.ts
- readme.md
- test.ts
> Don't use the same memoized function across instances when `.decorator()` is used

- index.ts
- test.ts
> Fix using multiple decorators on the same instance

- index.ts
Export the `Options` type so consumers can reference the type. This was exported in 6.1.1 and lost during the TypeScript refactor.
The only other way to reference the type is `Paramaters<typeof mem>[1]` which isn't very ergonomic, and doesn't expose the generic parameters.
> Export `Options` type from package

- index.ts
- package.json
- readme.md
- test.ts
> Use custom cache expiration logic

- index.ts
- readme.md
- test.ts
hey, first of all I really love your package ❤️ 
i have the use case to fetch the weather from an external api which should be memorized. 
the weather is dependent of the `address` and and `timestamp`. 
if the `timestamp` is in the past, the result should be cached infinite, otherwise for e. g. 1 hour. 
to make this happen the `maxAge` should be computed from the arguments (like the cache key) 
what do you think?
> Let `maxAge` option accept a function

- index.ts
Fixes #103
I haven't been able to write a test for it, but I believe this fixes #103. Even if not, it does fix a bug.
> Fix timer ID memory leak with `maxAge` option
